server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    dynamic:
      primary: xiumu
      datasource:
        xiumu:
          driver-class-name: org.h2.Driver
          url: jdbc:h2:file:./h2/data
          username: xiumu
          password: xiumu
          lazy: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2


mybatis-plus:
  type-enums-package: com.xiumu.common.core.enums;com.xiumu.generator.enums;
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true #驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






