server:
  port: 8080

spring:
  profiles:
    active: dev


---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///books?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///books?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

logging:
  level:
    com.tata.product.search.mapper: debug






