###  TokenController 登录接口测试
GET http://localhost:8080/token
Content-Type: application/json

{
  "username": "xiumu",
  "password": "123456"
}

###  TokenController 用户角色权限接口测试
GET http://localhost:8080/userRoleAuth
Content-Type: application/json
XiuMuToken: 3e1f1c84-7f98-41b8-8cf2-9619cf6bfe49

###  TokenController 退出登录 接口测试
GET http://localhost:8080/logout
Content-Type: application/json
XiuMuToken: 3e1f1c84-7f98-41b8-8cf2-9619cf6bfe49


###  TokenController 接口测试



###  UserController 接口测试
GET http://localhost:8080/user
Content-Type: application/json

{
  "username": "xiumu",
  "password": "123456"
}

###  接口测试


