### 查询
GET {{host}}/role
XiuMuToken: {{token}}

### 新增
POST {{host}}/role
Content-Type: application/json
XiuMuToken: {{token}}

{
  "roleName": "supperAdmin",
  "roleCode": "supper_admin",
  "roleDesc": "超级管理员"
}

### 修改
PUT {{host}}/role/1620733847266254849
Content-Type: application/json
XiuMuToken: {{token}}

{
  "roleName": "supperAdmin",
  "roleCode": "supper_admin",
  "roleDesc": "超级管理员"
}
### 设置 auth
PUT {{host}}/role/1620733847266254849/auth
Content-Type: application/json
XiuMuToken: {{token}}

["1620724830024245250", "1620728144690466818", "1620732519005675521"]