###  UserController 用户角色权限
GET {{host}}/user/user&role&auth
Content-Type: application/json
XiuMuToken: {{token}}

### 查询 user
GET {{host}}/user
XiuMuToken: {{token}}

### 添加用户
POST {{host}}/user
Content-Type: application/json

{
  "username": "lym",
  "password": "123456",
  "nickName": "昵称"
}

### 设置角色
PUT {{host}}/user/19971029/role
Content-Type: application/json
XiuMuToken: {{token}}

["1620733847266254849"]

###

### 删除 user
DELETE http://localhost:8080/user/1620710485882060801
